// Copyright (c) The OpenINF Authors. All rights reserved.
// This code is available under the MIT license found in the LICENSE file.

/**
 * Generates a complete message from all errors generated by predicates.
 * @param errors The errors generated by the predicates.
 * @param isAny If this function is called from the any argument.
 * @returns The error message.
 */
export function generateArgumentErrorMessage(
  errors: Map<string, Set<string>>,
  isAny = false
): string {
  const message = [];

  const errorArray = [...errors.entries()];

  const isAnyErrorWithoutOneItemOnly = errorArray.some(
    ([, array]) => array.size !== 1
  );

  // If only one error "key" is present, enumerate all of those errors only.
  if (errorArray.length === 1) {
    // length === 1 guarantees index 0 is present.
    // oxlint-disable-next-line typescript/no-unnecessary-type-assertion -- oxlint-tsgolint doesn't currently honor noUncheckedIndexedAccess; tsc does require this.
    const [, returnedErrors] = errorArray[0]!;

    if (!isAny && returnedErrors.size === 1) {
      // size === 1 guarantees the first iterated value is present.
      const [errorMessage] = returnedErrors;
      // oxlint-disable-next-line typescript/no-unnecessary-type-assertion -- oxlint-tsgolint doesn't currently honor noUncheckedIndexedAccess; tsc does require this.
      return errorMessage!;
    }

    for (const entry of returnedErrors) {
      message.push(`${isAny ? '  - ' : ''}${entry}`);
    }

    return message.join('\n');
  }

  // If every predicate returns just one error, enumerate them as is.
  if (!isAnyErrorWithoutOneItemOnly) {
    return errorArray.map(([, [item]]) => `  - ${item}`).join('\n');
  }

  // Else, iterate through all the errors and enumerate them.
  for (const [key, value] of errorArray) {
    message.push(`Errors from the "${key}" predicate:`);
    for (const entry of value) {
      message.push(`  - ${entry}`);
    }
  }

  return message.join('\n');
}
